import React from "react";
import { LegalLayout } from "./LegalLayout";

export const TermsContent = () => {
    return (
        <LegalLayout title="Terms of Service" lastUpdated="October 24, 2023">
            <h3>1. Acceptance of Terms</h3>
            <p>By accessing and using Genapps.online, you accept and agree to be bound by the terms and provision of this agreement.</p>

            <h3>2. Description of Service</h3>
            <p>Genapps.online provides an AI-powered software development platform. We reserve the right to modify, suspend, or discontinue the service at any time.</p>

            <h3>3. User Responsibilities</h3>
            <p>You are responsible for maintaining the confidentiality of your account and for all activities that occur under your login.</p>

            <h3>4. Intellectual Property</h3>
            <p>The code generated by Genapps.online for your specific projects belongs to you. The platform technology itself is owned by MUNEEB UR REHMAN.</p>

            <h3>5. Limitation of Liability</h3>
            <p>In no event shall Genapps.online or MUNEEB UR REHMAN be liable for any indirect, incidental, special, consequential or punitive damages.</p>
        </LegalLayout>
    );
};
