import React, { useState, useEffect, useRef } from 'react';
import { Check, Sparkles, Zap, Crown, Shield, ChevronDown, Lock, CreditCard } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { openCheckout } from '../lib/lemonsqueezy';
import { useNavigate, Link } from 'react-router-dom';
import { useToast } from '../context/ToastContext';

const plans = [
    {
        name: 'Starter',
        id: 'starter',
        icon: Zap,
        price: { monthly: 19, annual: 15 },
        description: 'Perfect for side projects and personal sites.',
        gradient: 'from-blue-500 to-cyan-500',
        features: [
            'Single-page website',
            '3 templates',
            'HTML + CSS + JS output',
            'Download code',
            'Mobile responsive',
            'Basic SEO',
        ],
        cta: 'Get Started',
        popular: false,
    },
    {
        name: 'Pro',
        id: 'pro',
        icon: Sparkles,
        price: { monthly: 49, annual: 39 },
        description: 'For startups and businesses that mean business.',
        gradient: 'from-brand-500 to-lavender-500',
        features: [
            'Multi-page website',
            'All 50+ templates',
            'React + Tailwind output',
            'Deploy to Vercel',
            'Push to GitHub',
            'Advanced SEO & analytics',
            'Custom domain support',
            'Priority AI generation',
        ],
        cta: 'Start Free Trial',
        popular: true,
    },
    {
        name: 'Business',
        id: 'business',
        icon: Crown,
        price: { monthly: 99, annual: 79 },
        description: 'Full-stack apps with database and auth.',
        gradient: 'from-orange-500 to-red-500',
        features: [
            'Everything in Pro',
            'Full-stack application',
            'Supabase database',
            'Authentication system',
            'API routes & backend',
            'Admin dashboard',
            'Custom integrations',
            'Dedicated support',
            'White-label option',
        ],
        cta: 'Contact Sales',
        popular: false,
    },
];

const faqs = [
    {
        q: 'Can I cancel my subscription anytime?',
        a: 'Yes! You can cancel at any time. Your subscription stays active until the end of the current billing period — no partial refunds, but you keep full access until then.',
    },
    {
        q: 'How does the 30-day money-back guarantee work?',
        a: 'If you\'re not satisfied within 30 days of your initial purchase, email us at refunds@genapps.online and we\'ll issue a full refund — no questions asked.',
    },
    {
        q: 'What payment methods do you accept?',
        a: 'We accept all major credit/debit cards (Visa, Mastercard, Amex), PayPal, and Apple Pay — all securely processed through Lemon Squeezy.',
    },
    {
        q: 'Will I be charged tax?',
        a: 'Tax (VAT/GST/Sales Tax) is calculated automatically based on your location and is handled by Lemon Squeezy, our Merchant of Record.',
    },
    {
        q: 'Can I switch between monthly and annual billing?',
        a: 'Yes! You can switch at any time. When upgrading to annual, you\'ll receive a prorated credit for the remainder of your current monthly billing period.',
    },
    {
        q: 'Do I own the generated code?',
        a: 'Absolutely. All code generated by Genapps is 100% yours. You can use it commercially, modify it, and distribute it without any restrictions.',
    },
];

function AnimatedPrice({ value }) {
    const [displayed, setDisplayed] = useState(value);
    const prevRef = useRef(value);

    useEffect(() => {
        if (prevRef.current !== value) {
            const start = prevRef.current;
            const end = value;
            const duration = 400;
            const startTime = Date.now();

            const animate = () => {
                const elapsed = Date.now() - startTime;
                const progress = Math.min(elapsed / duration, 1);
                const eased = 1 - Math.pow(1 - progress, 3);
                setDisplayed(Math.round(start + (end - start) * eased));
                if (progress < 1) requestAnimationFrame(animate);
            };
            requestAnimationFrame(animate);
            prevRef.current = value;
        }
    }, [value]);

    return <span>${displayed}</span>;
}

function FaqItem({ q, a }) {
    const [open, setOpen] = useState(false);
    return (
        <div className="border-b border-slate-200/50 last:border-0">
            <button
                onClick={() => setOpen(!open)}
                className="w-full flex items-center justify-between py-4 text-left group"
            >
                <span className="text-sm font-semibold text-slate-800 group-hover:text-brand-500 transition-colors">{q}</span>
                <ChevronDown className={`h-4 w-4 text-slate-400 flex-shrink-0 ml-4 transition-transform duration-300 ${open ? 'rotate-180' : ''}`} />
            </button>
            <div className={`overflow-hidden transition-all duration-300 ${open ? 'max-h-40 pb-4' : 'max-h-0'}`}>
                <p className="text-sm text-slate-500 leading-relaxed">{a}</p>
            </div>
        </div>
    );
}

export default function Pricing() {
    const [annual, setAnnual] = useState(false);
    const [loadingPlan, setLoadingPlan] = useState(null);
    const { subscription, user, isAuthenticated } = useAuth();
    const navigate = useNavigate();
    const { info: showInfo, error: showError } = useToast();

    const handleCheckout = async (plan) => {
        if (!isAuthenticated) {
            navigate('/signup');
            return;
        }

        if (subscription.plan === plan.id) return;

        setLoadingPlan(plan.id);
        try {
            const result = await openCheckout(plan.id, annual, {
                email: user?.email,
                name: user?.user_metadata?.name,
                userId: user?.id,
            });

            if (result.demo) {
                showInfo(`Checkout for ${plan.name} (${annual ? 'Annual' : 'Monthly'}) is in demo mode. Configure your Lemon Squeezy variant IDs in .env to enable real checkout.`);
            }
        } catch (err) {
            console.error('Checkout error:', err);
            showError('Checkout failed. Please try again.');
        } finally {
            setLoadingPlan(null);
        }
    };

    const getCtaText = (plan) => {
        if (subscription.plan === plan.id) return '✓ Current Plan';
        if (loadingPlan === plan.id) return 'Loading...';
        return plan.cta;
    };

    return (
        <section id="pricing" className="section-padding relative overflow-hidden">
            {/* Background */}
            <div className="absolute inset-0 pointer-events-none">
                <div className="cloud-shape cloud-shape-1 top-[5%] left-[30%] animate-cloud-drift opacity-30" />
                <div className="cloud-shape cloud-shape-2 bottom-[10%] right-[20%] animate-cloud-drift-reverse opacity-20" />
            </div>

            <div className="section-container relative z-10">
                <div className="text-center mb-16">
                    <span className="section-badge">Pricing</span>
                    <h2 className="section-title">
                        Simple, Transparent <span className="gradient-text">Pricing</span>
                    </h2>
                    <p className="section-subtitle">
                        Start free. Upgrade when you're ready. No hidden fees, no surprises.
                    </p>

                    {/* Toggle */}
                    <div className="flex items-center justify-center mt-8 space-x-4">
                        <span className={`text-sm font-medium ${!annual ? 'text-slate-900' : 'text-slate-400'}`}>Monthly</span>
                        <button
                            onClick={() => setAnnual(!annual)}
                            className={`relative w-14 h-7 rounded-full transition-colors duration-300 ${annual ? 'bg-brand-500' : 'bg-slate-300'
                                }`}
                        >
                            <div className={`absolute top-0.5 left-0.5 w-6 h-6 bg-white rounded-full shadow-md transition-transform duration-300 ${annual ? 'translate-x-7' : 'translate-x-0'
                                }`} />
                        </button>
                        <span className={`text-sm font-medium ${annual ? 'text-slate-900' : 'text-slate-400'}`}>
                            Annual
                            <span className="ml-2 text-xs text-emerald-500 font-semibold">Save 20%</span>
                        </span>
                    </div>

                    {/* What You Get */}
                    <div className="mt-10 mb-12 max-w-3xl mx-auto">
                        <div className="glass-card p-6 sm:p-8">
                            <h3 className="text-lg font-bold text-slate-900 font-display text-center mb-4">
                                What You <span className="gradient-text">Get</span>
                            </h3>
                            <p className="text-sm text-slate-500 text-center mb-6 leading-relaxed">
                                Genapps is a <strong className="text-slate-700">digital product</strong> — an AI-powered code generation platform. When you subscribe, you get:
                            </p>
                            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                                {[
                                    { title: 'AI-Generated Code', desc: 'Production-ready HTML, CSS, JS, React & Tailwind code — yours to keep forever.' },
                                    { title: 'Instant Downloads', desc: 'Download your generated website/app source code directly to your computer.' },
                                    { title: 'Cloud Deployment', desc: 'One-click deploy to Vercel or push to GitHub (Pro & Business plans).' },
                                ].map((item, i) => (
                                    <div key={i} className="text-center p-4 rounded-xl bg-white/50 border border-slate-200/30">
                                        <h4 className="text-sm font-bold text-slate-800 mb-1">{item.title}</h4>
                                        <p className="text-xs text-slate-500 leading-relaxed">{item.desc}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
                    {plans.map((plan) => {
                        const isCurrentPlan = subscription.plan === plan.id;

                        return (
                            <div
                                key={plan.name}
                                className={`relative rounded-3xl p-8 transition-all duration-500 ${plan.popular
                                    ? 'bg-white/80 backdrop-blur-xl border-2 border-brand-300 shadow-2xl scale-[1.02] lg:scale-105'
                                    : 'glass-card hover:shadow-lg'
                                    }`}
                                style={plan.popular ? { boxShadow: '0 16px 48px rgba(59,130,246,0.12)' } : {}}
                            >
                                {/* Popular Badge */}
                                {plan.popular && (
                                    <div className="absolute -top-4 left-1/2 -translate-x-1/2">
                                        <div className="bg-gradient-to-r from-brand-500 to-lavender-500 text-white text-xs font-bold px-4 py-1.5 rounded-full shadow-lg shadow-brand-500/30">
                                            ⚡ MOST POPULAR
                                        </div>
                                    </div>
                                )}

                                {/* Icon & Name */}
                                <div className="flex items-center space-x-3 mb-4">
                                    <div className={`flex items-center justify-center w-10 h-10 rounded-xl bg-gradient-to-r ${plan.gradient}`}>
                                        <plan.icon className="h-5 w-5 text-white" />
                                    </div>
                                    <h3 className="text-xl font-bold text-slate-900 font-display">{plan.name}</h3>
                                </div>

                                <p className="text-sm text-slate-500 mb-6">{plan.description}</p>

                                {/* Price */}
                                <div className="mb-8">
                                    <div className="flex items-baseline">
                                        <span className="text-5xl font-extrabold text-slate-900 font-display">
                                            <AnimatedPrice value={annual ? plan.price.annual : plan.price.monthly} />
                                        </span>
                                        <span className="text-slate-400 ml-2">/month</span>
                                    </div>
                                    {annual && (
                                        <p className="text-xs text-emerald-500 mt-1">
                                            Billed annually (${plan.price.annual * 12}/year)
                                        </p>
                                    )}
                                </div>

                                {/* CTA */}
                                <button
                                    onClick={() => handleCheckout(plan)}
                                    disabled={isCurrentPlan || loadingPlan === plan.id}
                                    className={`w-full py-3.5 px-6 rounded-2xl font-bold text-sm transition-all duration-300 mb-8 ${isCurrentPlan
                                        ? 'bg-emerald-50 text-emerald-600 border border-emerald-200/50 cursor-default'
                                        : plan.popular
                                            ? 'bg-gradient-to-r from-brand-500 to-lavender-500 text-white shadow-lg shadow-brand-500/25 hover:shadow-brand-500/40 hover:-translate-y-0.5'
                                            : 'bg-white/60 text-slate-700 hover:bg-white border border-slate-200/50 hover:-translate-y-0.5'
                                        }`}
                                >
                                    {getCtaText(plan)}
                                </button>

                                {/* Features */}
                                <ul className="space-y-3">
                                    {plan.features.map((feature, j) => (
                                        <li key={j} className="flex items-start space-x-3">
                                            <Check className={`h-4 w-4 mt-0.5 flex-shrink-0 ${plan.popular ? 'text-brand-500' : 'text-slate-400'
                                                }`} />
                                            <span className="text-sm text-slate-600">{feature}</span>
                                        </li>
                                    ))}
                                </ul>

                                {/* Money-back guarantee — all plans */}
                                <div className="mt-6 pt-6 border-t border-slate-200/50 flex items-center justify-center space-x-2">
                                    <Shield className="h-4 w-4 text-emerald-500" />
                                    <span className="text-xs text-slate-500">30-day money-back guarantee</span>
                                </div>
                            </div>
                        );
                    })}
                </div>

                {/* Secure Payment Badge */}
                <div className="mt-12 text-center">
                    <div className="inline-flex items-center gap-3 px-6 py-3 rounded-2xl bg-white/60 backdrop-blur-xl border border-white/50"
                        style={{ boxShadow: '0 4px 16px rgba(0,0,0,0.04)' }}
                    >
                        <Lock className="h-4 w-4 text-emerald-500" />
                        <span className="text-xs text-slate-500">Secure payment powered by</span>
                        <a href="https://www.lemonsqueezy.com" target="_blank" rel="noopener noreferrer" className="text-xs font-bold text-slate-700 hover:text-brand-500 transition-colors">🍋 Lemon Squeezy</a>
                        <span className="text-xs text-slate-400">|</span>
                        <CreditCard className="h-4 w-4 text-slate-400" />
                        <span className="text-xs text-slate-400">Visa • Mastercard • Amex • PayPal</span>
                    </div>
                </div>

                {/* FAQ Section */}
                <div className="mt-20 max-w-2xl mx-auto">
                    <h3 className="text-2xl font-bold text-slate-900 font-display text-center mb-2">
                        Frequently Asked <span className="gradient-text">Questions</span>
                    </h3>
                    <p className="text-sm text-slate-500 text-center mb-8">
                        Everything you need to know about billing and subscriptions.
                    </p>
                    <div className="glass-card p-6 sm:p-8">
                        {faqs.map((faq, i) => (
                            <FaqItem key={i} q={faq.q} a={faq.a} />
                        ))}
                    </div>
                    <p className="text-center mt-6 text-sm text-slate-400">
                        Still have questions? Read our{' '}
                        <Link to="/refund" className="text-brand-500 hover:text-brand-600 font-semibold transition-colors">Refund Policy</Link>
                        {' '}or{' '}
                        <Link to="/contact" className="text-brand-500 hover:text-brand-600 font-semibold transition-colors">Contact us</Link>.
                    </p>
                </div>
            </div>
        </section>
    );
}
