import React, { useState } from 'react';
import { ExternalLink, Eye, Clock, Zap } from 'lucide-react';

const showcaseItems = [
    {
        title: 'TechVenture AI',
        category: 'SaaS Startup',
        description: 'AI-powered analytics platform',
        gradient: 'from-brand-500 to-lavender-500',
        mockupBg: 'from-sky-100 to-blue-100',
        buildTime: '87s',
        views: '2.4k',
    },
    {
        title: 'FoodieHub',
        category: 'Restaurant',
        description: 'Modern restaurant booking site',
        gradient: 'from-orange-500 to-red-500',
        mockupBg: 'from-orange-50 to-red-50',
        buildTime: '94s',
        views: '1.8k',
    },
    {
        title: 'DevPortfolio Pro',
        category: 'Portfolio',
        description: 'Developer portfolio & blog',
        gradient: 'from-emerald-500 to-teal-500',
        mockupBg: 'from-emerald-50 to-teal-50',
        buildTime: '72s',
        views: '3.1k',
    },
    {
        title: 'StreamFlow',
        category: 'Streaming',
        description: 'Video streaming platform UI',
        gradient: 'from-red-500 to-pink-500',
        mockupBg: 'from-red-50 to-pink-50',
        buildTime: '108s',
        views: '1.2k',
    },
    {
        title: 'CloudSync',
        category: 'SaaS Dashboard',
        description: 'Cloud management dashboard',
        gradient: 'from-cyan-500 to-blue-500',
        mockupBg: 'from-cyan-50 to-blue-50',
        buildTime: '95s',
        views: '2.7k',
    },
    {
        title: 'BeatWave',
        category: 'Music App',
        description: 'Music streaming web app',
        gradient: 'from-green-500 to-emerald-500',
        mockupBg: 'from-green-50 to-emerald-50',
        buildTime: '82s',
        views: '1.5k',
    },
];

const categories = ['All', 'SaaS', 'Restaurant', 'Portfolio', 'Streaming', 'Music'];

export default function Showcase() {
    const [activeCategory, setActiveCategory] = useState('All');

    const filteredItems = activeCategory === 'All'
        ? showcaseItems
        : showcaseItems.filter(item =>
            item.category.toLowerCase().includes(activeCategory.toLowerCase())
        );

    return (
        <section id="showcase" className="section-padding relative overflow-hidden">
            {/* Background */}
            <div className="absolute inset-0 pointer-events-none">
                <div className="cloud-shape cloud-shape-1 top-[10%] left-[10%] animate-cloud-drift opacity-30" />
            </div>

            <div className="section-container relative z-10">
                <div className="text-center mb-12">
                    <span className="section-badge">Showcase</span>
                    <h2 className="section-title">
                        Built with <span className="gradient-text">Genapps</span>
                    </h2>
                    <p className="section-subtitle">
                        Real websites generated by our AI. Every one of these was created in under 2 minutes.
                    </p>
                </div>

                {/* Category Filter */}
                <div className="flex justify-center flex-wrap gap-2 mb-10">
                    {categories.map((cat) => (
                        <button
                            key={cat}
                            onClick={() => setActiveCategory(cat)}
                            className={`px-4 py-2 rounded-full text-sm font-medium transition-all duration-300 ${activeCategory === cat
                                ? 'bg-brand-50 text-brand-600 border border-brand-200/50'
                                : 'bg-white/40 text-slate-500 border border-white/30 hover:bg-white/60 hover:text-slate-700'
                                }`}
                        >
                            {cat}
                        </button>
                    ))}
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
                    {filteredItems.map((item, i) => (
                        <div key={i} className="group relative rounded-3xl overflow-hidden border border-white/40 bg-white/50 backdrop-blur-lg hover:shadow-xl transition-all duration-500 hover:-translate-y-1"
                            style={{ boxShadow: '0 4px 24px rgba(0,0,0,0.06)' }}
                        >
                            {/* Mockup Preview */}
                            <div className={`relative h-48 bg-gradient-to-br ${item.mockupBg} overflow-hidden`}>
                                {/* Fake browser chrome */}
                                <div className="absolute top-3 left-3 flex space-x-1.5">
                                    <div className="w-2.5 h-2.5 rounded-full bg-red-400/60" />
                                    <div className="w-2.5 h-2.5 rounded-full bg-yellow-400/60" />
                                    <div className="w-2.5 h-2.5 rounded-full bg-green-400/60" />
                                </div>

                                {/* Fake content lines */}
                                <div className="mt-10 px-5 space-y-3">
                                    <div className={`h-4 w-3/4 rounded-full bg-gradient-to-r ${item.gradient} opacity-25`} />
                                    <div className="h-3 w-1/2 rounded-full bg-slate-300/30" />
                                    <div className="h-3 w-2/3 rounded-full bg-slate-300/30" />
                                    <div className="flex space-x-2 mt-4">
                                        <div className={`h-8 w-24 rounded-lg bg-gradient-to-r ${item.gradient} opacity-30`} />
                                        <div className="h-8 w-20 rounded-lg bg-slate-300/20" />
                                    </div>
                                    <div className="grid grid-cols-3 gap-2 mt-3">
                                        <div className="h-12 rounded-lg bg-white/30" />
                                        <div className="h-12 rounded-lg bg-white/30" />
                                        <div className="h-12 rounded-lg bg-white/30" />
                                    </div>
                                </div>

                                {/* Hover Overlay */}
                                <div className="absolute inset-0 bg-slate-900/50 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center space-x-3">
                                    <button className="px-4 py-2 rounded-xl bg-white text-slate-900 text-sm font-semibold flex items-center space-x-2 hover:bg-slate-100 transition-colors">
                                        <Eye className="h-4 w-4" />
                                        <span>Preview</span>
                                    </button>
                                    <button className="px-4 py-2 rounded-xl bg-white/20 text-white text-sm font-medium flex items-center space-x-2 border border-white/30 hover:bg-white/30 transition-colors backdrop-blur-sm">
                                        <ExternalLink className="h-4 w-4" />
                                        <span>Visit</span>
                                    </button>
                                </div>
                            </div>

                            {/* Info */}
                            <div className="p-5">
                                <div className="flex items-center justify-between mb-2">
                                    <div className={`inline-block text-xs font-semibold px-2.5 py-1 rounded-full bg-gradient-to-r ${item.gradient} text-white`}>
                                        {item.category}
                                    </div>
                                    <div className="flex items-center space-x-3 text-xs text-slate-400">
                                        <span className="flex items-center space-x-1">
                                            <Clock className="w-3 h-3" />
                                            <span>{item.buildTime}</span>
                                        </span>
                                        <span className="flex items-center space-x-1">
                                            <Eye className="w-3 h-3" />
                                            <span>{item.views}</span>
                                        </span>
                                    </div>
                                </div>
                                <h3 className="text-lg font-bold text-slate-900 mb-1">{item.title}</h3>
                                <p className="text-sm text-slate-500">{item.description}</p>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="text-center mt-12">
                    <a href="#generator" className="btn-secondary sparkle-btn">
                        Build Yours Now
                        <ExternalLink className="ml-2 h-4 w-4" />
                    </a>
                </div>
            </div>
        </section>
    );
}
