/**
 * Project Store
 * Manages project state, persistence, and export functionality
 */

import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export interface ProjectFile {
    path: string;
    content: string;
    language: string;
}

export interface ProjectState {
    id: string;
    name: string;
    files: ProjectFile[];
    createdAt: string;
    updatedAt: string;
}

export interface ProjectHistory {
    past: ProjectState[];
    present: ProjectState;
    future: ProjectState[];
}

const STORAGE_KEY = 'genapps_project';
const MAX_HISTORY = 50;

/**
 * Generate a unique project ID
 */
export function generateProjectId(): string {
    return `proj_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
}

/**
 * Get file language from extension
 */
export function getLanguageFromPath(path: string): string {
    const ext = path.split('.').pop()?.toLowerCase() || '';
    const langMap: Record<string, string> = {
        'js': 'javascript',
        'jsx': 'jsx',
        'ts': 'typescript',
        'tsx': 'tsx',
        'css': 'css',
        'html': 'html',
        'json': 'json',
        'md': 'markdown',
        'svg': 'xml'
    };
    return langMap[ext] || 'text';
}

/**
 * Create a new empty project
 */
export function createEmptyProject(name: string = 'Untitled Project'): ProjectState {
    return {
        id: generateProjectId(),
        name,
        files: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    };
}

/**
 * Save project to localStorage
 */
export function saveProject(project: ProjectState): void {
    const updated = {
        ...project,
        updatedAt: new Date().toISOString()
    };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    console.log('Project saved:', updated.name);
}

/**
 * Load project from localStorage
 */
export function loadProject(): ProjectState | null {
    try {
        const data = localStorage.getItem(STORAGE_KEY);
        if (data) {
            return JSON.parse(data) as ProjectState;
        }
    } catch (error) {
        console.error('Failed to load project:', error);
    }
    return null;
}

/**
 * Clear saved project
 */
export function clearProject(): void {
    localStorage.removeItem(STORAGE_KEY);
}

/**
 * Export project as ZIP file
 */
export async function exportProjectAsZip(project: ProjectState): Promise<void> {
    const zip = new JSZip();

    // Add all files to the zip
    for (const file of project.files) {
        zip.file(file.path, file.content);
    }

    // Add a README
    const readme = `# ${project.name}

Generated by GenApps.online

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Project Info
- Created: ${project.createdAt}
- Last Updated: ${project.updatedAt}
`;
    zip.file('README.md', readme);

    // Generate and download
    const content = await zip.generateAsync({ type: 'blob' });
    const filename = `${project.name.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.zip`;
    saveAs(content, filename);
}

/**
 * Convert project files to a flat object for WebContainer mounting
 */
export function filesToMountable(files: ProjectFile[]): Record<string, string> {
    const result: Record<string, string> = {};
    for (const file of files) {
        result[file.path] = file.content;
    }
    return result;
}

/**
 * Create project history manager
 */
export function createProjectHistory(initial: ProjectState): ProjectHistory {
    return {
        past: [],
        present: initial,
        future: []
    };
}

/**
 * Push a new state to history (for undo/redo)
 */
export function pushToHistory(history: ProjectHistory, newState: ProjectState): ProjectHistory {
    const past = [...history.past, history.present].slice(-MAX_HISTORY);
    return {
        past,
        present: newState,
        future: []
    };
}

/**
 * Undo to previous state
 */
export function undo(history: ProjectHistory): ProjectHistory {
    if (history.past.length === 0) return history;

    const previous = history.past[history.past.length - 1];
    const newPast = history.past.slice(0, -1);

    return {
        past: newPast,
        present: previous,
        future: [history.present, ...history.future]
    };
}

/**
 * Redo to next state
 */
export function redo(history: ProjectHistory): ProjectHistory {
    if (history.future.length === 0) return history;

    const next = history.future[0];
    const newFuture = history.future.slice(1);

    return {
        past: [...history.past, history.present],
        present: next,
        future: newFuture
    };
}

/**
 * Check if undo is available
 */
export function canUndo(history: ProjectHistory): boolean {
    return history.past.length > 0;
}

/**
 * Check if redo is available
 */
export function canRedo(history: ProjectHistory): boolean {
    return history.future.length > 0;
}

/**
 * Generate a shareable deploy link (mock for now)
 */
export function generateDeployLink(projectId: string): string {
    // In a real app, this would call a backend API
    // For now, generate a mock link
    const hash = btoa(projectId).replace(/[+/=]/g, '').substring(0, 8);
    return `https://preview.genapps.online/${hash}`;
}

/**
 * Copy project files to clipboard as JSON
 */
export async function copyProjectToClipboard(project: ProjectState): Promise<void> {
    const data = JSON.stringify(project, null, 2);
    await navigator.clipboard.writeText(data);
}
